[project]
name = "tubes2-if3270-ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.3",
    "scikit-learn>=1.6.1",
    "tensorflow>=2.19.0",
    "tensorflow-metal>=1.2.0",
]
